<a href="https://colab.research.google.com/github/GrandProgrammer/GrandProgrammer/blob/main/AMALIYOT_PRACTICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
np.array([1,2,3,4,5,6,7,8,9,0])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr.itemsize   # MEMORY IN DISK 1!-:>

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
help(np.add)   # HELP GIVES INFO ABOUT FUNCTION 1!-:>

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan

---

iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.

---





`💡Ishora` array[12]

In [ ]:
ar_zero = np.zeros(12)
ar_zero[5]=1
ar_zero

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
ar = np.arange(20,60)
ar

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arry = np.arange(1,11)
reversed_array = arry[::-1]
reversed_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
ar = np.arange(12,21).reshape(3,3)
ar

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
ar = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(ar)    # FINDS THE INDEXES OF THE ELEMENT WHICH ARE NOT EQUAL T-u 0

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
d_3 = np.random.random((2,2,2))   # ( () )
d_3

array([[[0.78958652, 0.80321264],
        [0.98607433, 0.73322728]],

       [[0.62648695, 0.288328  ],
        [0.82718086, 0.1299044 ]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arry = np.random.randn(9,9)
arry.min()
arry.max()

1.848075197362008

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
False


False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr_1 = np.random.randn(6,3)
arr_2 = np.random.random((3,4))
value = np.dot(arr_1 , arr_2)

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9   # sum(range(5), -1 )   # -1 + 0 ~ 5 = 9

9

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
ar = np.arange(1,11)
ar1 = np.arange(11,21)
ar1 > ar   # CHECKS EACH ELEMENT IN INDEXES 1!:->

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print('nan', "0", 'nan')   # 0 / 0  nan , 0 // 0  = 0 , nan is nan it doesnt matter if the astype float or integer 1!-:>

nan 0 nan


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
ar1 = np.arange(1,11)
ar2 = np.arange(6,16)
np.intersect1d(ar1, ar2)   # intersect1d

array([ 6,  7,  8,  9, 10])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
ar = np.random.randn(2,2)
np.floor(ar)
np.trunc(ar)
ar.astype(int)

array([[0, 0],
       [0, 0]])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
a_r = np.arange(9).reshape(3,3)
a_r[1:] = np.random.randn()
a_r

array([[0, 1, 2],
       [0, 0, 0],
       [0, 0, 0]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
art = np.array([-1,0,-3,4,5,6,7,8,9,11])
art.sort()
art

array([-3, -1,  0,  4,  5,  6,  7,  8,  9, 11])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
a = np.arange(10)
b = np.arange(6,16)
result = np.allclose(a,b)
result
rst = np.array_equal(a,b)
rst
# [a,b,c]  should be equal = [a,b,c]

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
a = np.random.randn(6,3)
b = np.random.randn(3,4)
result = np.dot(a,b)
result

array([[ 1.00607587, -0.21707459, -0.69239388, -2.0937902 ],
       [ 2.98023753, -1.96400195,  0.52380022, -4.24507012],
       [ 0.55258181, -0.66601848,  0.45405995, -0.45340208],
       [-0.0545213 ,  1.19688922, -0.39940356, -0.72345904],
       [-0.73592079,  2.22782132, -0.50575471, -0.05195568],
       [-0.89019469,  2.58771866, -0.33709283,  0.12820034]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
arr = np.arange(1,6)
a = np.argmax(arr)  # TAKES MAX INDEX OF ARRAY USING ARRAY WITH VARIABLE 1!-:>
arr[a] = 0
arr

array([1, 2, 3, 4, 0])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
bugun = np.datetime64('today','D')
a = np.datetime64('today', 'D') + np.timedelta64(1,'D')
a

numpy.datetime64('2023-11-13')

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
dates = np.datetime64("2016-01-01")   # SANA
total_days = np.arange(31)   # 31 KUN OY
total = dates + total_days   # HAR BIRINI RANGE GA MOSLA 1!-:>
total #

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
a_r = np.random.randn(10) # 10 ta TASODIFIY RANDOM SON 1!-:>
np.floor(a_r)
a_r.astype(int)
np.trunc(a_r)

array([-1., -0.,  0., -0.,  0., -1., -1.,  1.,  0.,  0.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
arr = np.arange(11)
arr.sum()
np.add.reduce(arr)
# sum

55

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
a = np.array([1, 2, 3, 4, 5])
# a[::2]  # CHAPDAN ONGA QARAB HAR 2 CHI ELEMENTNI OLISH
a[1::4] = 0   # 1 dan 4 gacha 3 ta element BOR , SHULARNING HAMMASINI 0 GA TENGLASH 1!-:>
a[3::4] = 0
a

array([1, 0, 3, 0, 5])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
from numpy.lib import stride_tricks
from numpy.lib.stride_tricks import as_strided

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
# YECHIM YO'Q YORDAM KERAK 1!-:>

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
a_1 = np.array([0.71, -0.22, 1.6, 0.05, 0.81])
a_11 = np.array([0.71, -0.21, 1.6, 0.05, 0.81])
np.intersect1d(a_1,a_11)  # O'XSHASHLARNI TOPADI 1!-:>
#
w = np.array([0.3, 0.5, 0.2, 0.7, 1., -0.6]) # weights
x = np.array([0, 1, 1, 2, 2, 2])
np.bincount(x,  weights=w)


array([0.3, 0.7, 1.1])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [ ]:
# Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
# YECHIM KERAK 1!-:>